language: node_js
node_js:
  - "stable"
addons:
  code_climate:
  repo_token: $mytoken
cache:
  directories:
    - node_modules
before_script:
  - yarn global add codeclimate-test-reporter
script:
  - yarn add --dev coveralls
  - yarn test -- --coverage
after_success:
  - yarn run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls