language: node_js
node_js:
  - "stable"
addons:
  code_climate:
  repo_token: $mytoken
cache:
  directories:
    - node_modules
before_script:
  - npm install -g codeclimate-test-reporter
script:
  - npm run test
after_success:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
